const CLEAR_ALL_DONE = "CLEAR_ALL_DONE";
const CHANGE_CHECKBOX_STATE = "CHANGE_CHECKBOX-STATE";
const HANDLE_ADD_DATA = "HANDLE_ADD_DATA";
const HANDLE_MARK_AS_NOT_DONE = "HANDLE_MARK_AS_NOT_DONE";
const HANDLE_MARK_AS_DONE = "HANDLE_MARK_AS_DONE";

export const ActionsTypes = {
  CLEAR_ALL_DONE,
  CHANGE_CHECKBOX_STATE,
  HANDLE_ADD_DATA,
  HANDLE_MARK_AS_NOT_DONE,
  HANDLE_MARK_AS_DONE
};
